version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem-volume:/usr/local/bundle
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH_BASE_URL: ${OAUTH_BASE_URL}
      TWEET_BASE_URL: ${TWEET_BASE_URL}

volumes:
  gem-volume:
